### ISSUE TITLE
Supporting node.js version 12.19.0

### ISSUE THREAD

**Issue by neelahagga** [Mathieu2301/TradingView-API#64]
I am trying to use your TradingView-API in a personal android project, and am using this library for node.js: https://github.com/janeasystems/nodejs-mobile
It seems to support [no more than 12.19.0](https://github.com/janeasystems/nodejs-mobile/releases)
I do not have much experience from javascript; this error is what made me think it is a version problem:
```
src/miscRequests.js:296
          plots[plot.id] = `${plots[plot.target] ?? plot.target}_${plot.type}`;
                                                  ^
    
    SyntaxError: Unexpected token '?'
        at wrapSafe (internal/modules/cjs/loader.js:931:16)
        at Module._compile (internal/modules/cjs/loader.js:979:27)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
        at Module.load (internal/modules/cjs/loader.js:879:32)
        at Function.Module._load (internal/modules/cjs/loader.js:724:14)
        at Module.require (internal/modules/cjs/loader.js:903:19)
        at require (internal/modules/cjs/helpers.js:74:18)
        at Object.<anonymous> (/data/data/in.tg.jhaarsi/files/JhaaRSIProjectX/main.js:1:22)
        at Module._compile (internal/modules/cjs/loader.js:1015:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
```
I tested the same script on pc and termux too (node.js 14.16.0) and it seems to work fine.
Is there anything I can do to make it work on 12.19.0?

Alternatively, how can the problematic part be removed entirely (not loaded). My use is restricted to:
new TradingView.Client(),   new client.Session.Chart(),   chart.setMarket,   TradingView.getIndicator('STD;RSI'),   new chart1.Study (just RSI), study's onUpdate, study's periods.

**Comment by Mathieu2301** [comment]
Yes, you can replace `??` by `||` and it should work.

**Comment by Mathieu2301** [comment]
Hmmm weird... Maybe remove all the `#` 🤔

**Comment by Mathieu2301** [comment]
Okay so you should also replace all `sendQueue()` to `emitQueue()` in `client.js` file because there are a variable and a function both called `sendQueue`.

**Comment by neelahagga** [comment]
Replaced all the hashes and ?? from what I saw as identifiers (java terminology) in src folder.
Then a cannot find symbol relating to sendQueue() fired up. As you told already, I replaced sendQueue() by emitQueue() (there were 6 `sendQueue`s not followed by a `()` and I didn't touch them.

Finally, no errors are being thrown.
But before I take a sigh of relief, I find that indicator's onUpdate is never called (below code):
```
  const jrsi1 = new chart1.Study(indic);
  jrsi1.onUpdate((changes) => {
    if (!jrsi1.periods[0]) return;
     console.log(sym1.sym+'\u0965'+ jrsi1.periods[0].RSI);
  });
```

**Comment by Mathieu2301** [comment]
Can you do something like :
```javascript
setInterval(() => {
  console.log('Periods:', jrsi1.periods);
}, 1000);
```

to see if the code gets the data ?

**Comment by neelahagga** [comment]
> ```js
> setInterval(() => {
>   console.log('Periods:', jrsi1.periods);
> }, 1000);
> ```
It does print values:
```
 Periods: {
      '1644334260': {
        '$time': 1644334260,
        RSI: 55.84682671,
        RSIbased_MA: 61.19059693,
        Upper_Bollinger_Band: 1e+100,
        Lower_Bollinger_Band: 1e+100,
        fill_1_colorer: 1e+100
      },
      '1644334320': {
        '$time': 1644334320,
        RSI: 53.80652699,
        RSIbased_MA: 60.21737763,
        Upper_Bollinger_Band: 1e+100,
        Lower_Bollinger_Band: 1e+100,
        fill_1_colorer: 1e+100
      }.................
```
but `jrsi1.periods[0]` is somehow undefined.

**Comment by Mathieu2301** [comment]
Okay interesting

**Comment by Mathieu2301** [comment]
In `src/chart/session.js`, line 140, replace `get periods() {` by `get getPeriods() {`.
Then, use `jrsi1.getPeriods[0].RSI` instead of `jrsi1.periods[0].RSI`.

**Comment by neelahagga** [comment]
Still no luck
` Cannot read property '0' of undefined`

```
  setInterval(() => {
  try{console.log('Periods: ', jrsi1.getPeriods[0].RSI);}catch(err){console.error("Corona: ", err);}
}, 1000);

```

**Comment by neelahagga** [comment]
Is periods[0].RSI the only way to get the last value of RSI?
If there's no other way, can JSON.stringify() be manipulated with reasonable efficiency to get last value of RSI?

**Comment by Mathieu2301** [comment]
Oh sorry, you also have to do it in `src/chart/session.js`, line 129.

**Comment by Mathieu2301** [comment]
Yes we can use something like
```js
const lastRSI = Object.values(this.periods).sort((a, b) => b.$time - a.$time)[0].RSI;
```

**Comment by neelahagga** [comment]
> Yes we can use something like
> 
> ```js
> const lastRSI = Object.values(jrsi1.periods).sort((a, b) => b.$time - a.$time)[0].RSI;
> ```
Thanks a lot.
This works. (Facepalming) I should have asked about it earlier.
Also, if we remove `[0].RSI` in above code do we not get the same thing as jrsi1.periods?

**Comment by Mathieu2301** [comment]
> Also, if we remove `[0].RSI` in above code do we not get the same thing as jrsi1.periods?

Yes

**Comment by mohamad-supangat** [comment]
hai @Mathieu2301 because your resporn return 
```

 Periods: {
      '1644334260': {
        '$time': 1644334260,
        RSI: 55.84682671,
        RSIbased_MA: 61.19059693,
        Upper_Bollinger_Band: 1e+100,
        Lower_Bollinger_Band: 1e+100,
        fill_1_colorer: 1e+100
      },
      '1644334320': {
        '$time': 1644334320,
        RSI: 53.80652699,
        RSIbased_MA: 60.21737763,
        Upper_Bollinger_Band: 1e+100,
        Lower_Bollinger_Band: 1e+100,
        fill_1_colorer: 1e+100
      }
}
```

you should use 
```
jrsi1.periods['1644334320'].RSI
```

because your key is 1644334320

**Comment by mohamad-supangat** [comment]
i love android as my server, just sugestion @Mathieu2301  don't use termux as server, use real linux
i am using chroot container for my android server. and it works best 

https://github.com/mohamad-supangat/charch_dinit
